spring.application.name=userservicedecmwfeve
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://localhost:3306/userServices
spring.datasource.username=userServices
spring.datasource.password=NewStrongP@ssw0rd!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

